[HIVE-279]  Community Drawer amend.
Financial-Times/origami-navigation-service pull request #282
Opened 2021-09-08 15:26 UTC by milen

Changed community label to a parent item.

*FT Community *
FT Live - live.ft.com
FT Forums - forums.ft.com
Board Director Programme - bdp.ft.com

2021-09-13 07:49 UTC, maxcbc requested changes
Could you revert the changes to package-lock.json? No need to risk dependency changes in this PR.
Other than that looks good.

2021-09-13 09:29 UTC, JakeChampion approved these changes

2021-09-14 12:53 UTC, maxcbc approved these changes

2021-09-14 12:53 UTC, merged

2021-09-14 12:53 UTC, origamiserviceuser commented
:tada: This PR is included in version v117.0.3 :tada: